# Generated by Django 5.1.2 on 2024-10-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudweb', '0002_cliente_alter_dominio_nombre_dominio_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='costo_renovacion',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
