# Generated by Django 5.1.2 on 2024-10-15 01:27

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudweb', '0003_alter_dominio_costo_renovacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Ingresar número fijo o movil de forma internacional (+56XXXXXXXX)', max_length=128, region='CL', unique=True),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='costo_renovacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
    ]
