# Generated by Django 5.1.2 on 2024-10-19 09:23

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudweb', '0004_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Ingresar número fíjo o móvil de forma internacional, Ejemplo:+56XXXXXXXX', max_length=128, region='CL', unique=True),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='costo_renovacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
